apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-003-pipeline-aws: 1.0.46
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-003-pipeline-aws: 1.0.46
  template:
    metadata:
      labels:
        app: devops-003-pipeline-aws: 1.0.46
    spec:
      containers:
      - name: devops-003-pipeline-aws: 1.0.46
        image: mimaraslan/devops-003-pipeline-aws: 1.0.46
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8083
