apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-003-pipeline-aws:1.0.66
spec:
  replicas: 5
  selector:
    matchLabels:
      app: devops-003-pipeline-aws:1.0.66
  template:
    metadata:
      labels:
        app: devops-003-pipeline-aws:1.0.66
    spec:
      containers:
      - name: devops-003-pipeline-aws:1.0.66
        image: mimaraslan/devops-003-pipeline-aws:1.0.66
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8083
